"""Create initial stock data tables with PostgreSQL candle partitions."""

from alembic import op
import sqlalchemy as sa

revision = "20260713_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    dialect_name = op.get_bind().dialect.name
    op.create_table(
        "stocks",
        sa.Column("symbol", sa.String(16), primary_key=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("market", sa.String(20), nullable=False),
        sa.Column("sector", sa.String(120), nullable=False),
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )

    if dialect_name == "postgresql":
        op.execute("""
            CREATE TABLE stock_candles (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                symbol VARCHAR(16) NOT NULL REFERENCES stocks(symbol),
                timestamp TIMESTAMPTZ NOT NULL,
                interval VARCHAR(8) NOT NULL,
                data_stage VARCHAR(12) NOT NULL,
                aggregation_version VARCHAR(24) NOT NULL,
                open NUMERIC(20,6) NOT NULL,
                high NUMERIC(20,6) NOT NULL,
                low NUMERIC(20,6) NOT NULL,
                close NUMERIC(20,6) NOT NULL,
                volume BIGINT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                PRIMARY KEY (id, timestamp),
                CONSTRAINT uq_stock_candle_identity UNIQUE
                    (symbol, timestamp, interval, data_stage, aggregation_version)
            ) PARTITION BY RANGE (timestamp)
        """)
        op.execute("CREATE TABLE stock_candles_default PARTITION OF stock_candles DEFAULT")
        op.execute(
            "CREATE INDEX ix_stock_candles_lookup ON stock_candles (symbol, interval, data_stage, timestamp)"
        )
    else:
        op.create_table(
            "stock_candles",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("symbol", sa.String(16), sa.ForeignKey("stocks.symbol"), nullable=False),
            sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
            sa.Column("interval", sa.String(8), nullable=False),
            sa.Column("data_stage", sa.String(12), nullable=False),
            sa.Column("aggregation_version", sa.String(24), nullable=False),
            sa.Column("open", sa.Numeric(20, 6), nullable=False),
            sa.Column("high", sa.Numeric(20, 6), nullable=False),
            sa.Column("low", sa.Numeric(20, 6), nullable=False),
            sa.Column("close", sa.Numeric(20, 6), nullable=False),
            sa.Column("volume", sa.BigInteger(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
            sa.UniqueConstraint(
                "symbol",
                "timestamp",
                "interval",
                "data_stage",
                "aggregation_version",
                name="uq_stock_candle_identity",
            ),
        )
        op.create_index(
            "ix_stock_candles_lookup",
            "stock_candles",
            ["symbol", "interval", "data_stage", "timestamp"],
        )

    op.create_table(
        "data_quality_logs",
        sa.Column(
            "id",
            sa.BigInteger() if dialect_name == "postgresql" else sa.Integer(),
            primary_key=True,
            autoincrement=True,
        ),
        sa.Column("symbol", sa.String(16), nullable=False),
        sa.Column("rule", sa.String(80), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("ix_quality_logs_symbol_created", "data_quality_logs", ["symbol", "created_at"])


def downgrade() -> None:
    op.drop_table("data_quality_logs")
    op.drop_table("stock_candles")
    op.drop_table("stocks")
